# Generated by Django 4.1.7 on 2023-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_alter_recurring_invoice_cust_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='recur_itemtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('taxamt', models.IntegerField()),
                ('shipcharge', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
