# Generated by Django 4.1.7 on 2023-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_recur_itemtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recur_itemtable',
            name='shipcharge',
        ),
        migrations.RemoveField(
            model_name='recur_itemtable',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='recur_itemtable',
            name='taxamt',
        ),
        migrations.RemoveField(
            model_name='recur_itemtable',
            name='total',
        ),
        migrations.AddField(
            model_name='recur_itemtable',
            name='amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recur_itemtable',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recur_itemtable',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recur_itemtable',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recur_itemtable',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
