# Generated by Django 4.1.7 on 2023-06-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_remove_recur_itemtable_shipcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recur_itemtable',
            name='ri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.recurring_invoice'),
        ),
    ]
