# Generated by Django 4.1.7 on 2023-07-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_recurring_invoice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='repeat_every',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
